LOGIN = "kahoumou"

SERVER = "#{LOGIN}S"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.box = "josedom24/debian13"
  config.vm.box_check_update = false

  # Pas de dossier partagé nécessaire :
  # Ansible transfère les fichiers Kubernetes.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    # QEMU logiciel car KVM imbriqué faisait planter VirtualBox.
    libvirt.driver = "qemu"
    libvirt.uri = "qemu:///system"

    # Réseau de management Vagrant / SSH.
    libvirt.management_network_name = "vagrant-libvirt"
    libvirt.management_network_address = "192.168.121.0/24"
    libvirt.management_network_mode = "nat"
    libvirt.management_network_autostart = true
  end

  config.vm.define SERVER do |server|

    server.vm.hostname = SERVER

    # IP exigée pour la Partie 2.
    server.vm.network "private_network",
      ip: SERVER_IP,
      libvirt__network_name: "iot-p2",
      libvirt__netmask: "255.255.255.0",
      libvirt__host_ip: "192.168.56.1",
      libvirt__forward_mode: "nat",
      libvirt__dhcp_enabled: false

    server.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "confs/ansible/bootstrap.yml"
      ansible.compatibility_mode = "2.0"
      ansible.become = true
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "confs/ansible/server.yml"
      ansible.compatibility_mode = "2.0"
      ansible.become = true

      ansible.host_vars = {
        SERVER => {
          "server_ip" => SERVER_IP
        }
      }
    end
  end
end
