LOGIN = "kahoumou"

SERVER_NAME = "#{LOGIN}S"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.ssh.insert_key = false
  config.vm.boot_timeout = 600
  config.ssh.connect_timeout = 600

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = "p2-#{SERVER_NAME}"
      vb.memory = 2048
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
