
LOGIN = "kahoumou"

SERVER_NAME = "#{LOGIN}S"
WORKER_NAME = "#{LOGIN}SW"

SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  # Base Debian stable pour K3s
  config.vm.box = "debian/bookworm64"

  # Évite que Vagrant régénère une clé SSH différente à chaque création.
  # Cela stabilise les connexions vagrant ssh.
  config.ssh.insert_key = false

  # Délais plus larges car VirtualBox peut être lent au démarrage.
  config.vm.boot_timeout = 600
  config.ssh.connect_timeout = 600

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME

    # Réseau privé demandé pour communiquer avec le worker.
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = 2048
      vb.cpus = 1

      # Correction stabilité VirtualBox sur ta machine.
      vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
    end

    # Script d'installation K3s server.
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME

    # Réseau privé demandé pour rejoindre le serveur K3s.
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
      vb.memory = 2048
      vb.cpus = 1

      # Correction stabilité VirtualBox sur ta machine.
      vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
    end

    # Script d'installation K3s agent.
    worker.vm.provision "shell", path: "scripts/agent.sh"
  end
end
