LOGIN = "kahoumou"

SERVER = "#{LOGIN}S"
WORKER = "#{LOGIN}SW"

LAST_NODE = WORKER

NODES = {
  SERVER => {
    ip: "192.168.56.110",
    memory: 2048,
    cpus: 2
  },

  WORKER => {
    ip: "192.168.56.111",
    memory: 2048,
    cpus: 2
  }
}

Vagrant.configure("2") do |config|

  # Debian 13 compatible avec le provider Libvirt.
  config.vm.box = "josedom24/debian13"
  config.vm.box_check_update = false

  # Aucun dossier /vagrant partagé n'est nécessaire :
  # Ansible travaille depuis la machine principale via SSH.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Configuration générale du provider Libvirt/QEMU.
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.uri = "qemu:///system"

    # Réseau utilisé par Vagrant pour se connecter aux VMs en SSH.
    libvirt.management_network_name = "vagrant-libvirt"
    libvirt.management_network_address = "192.168.121.0/24"
    libvirt.management_network_mode = "nat"
    libvirt.management_network_autostart = true
  end

  NODES.each do |name, machine|

    config.vm.define name do |node|

      # Hostname :
      # kahoumouS / kahoumouSW
      node.vm.hostname = name

      # Réseau privé demandé pour le projet.
      node.vm.network "private_network",
        ip: machine[:ip],
        libvirt__network_name: "iot-p1",
        libvirt__netmask: "255.255.255.0",
        libvirt__host_ip: "192.168.56.1",
        libvirt__forward_mode: "nat",
        libvirt__dhcp_enabled: false

      # Ressources de chaque VM.
      node.vm.provider :libvirt do |libvirt|
        libvirt.memory = machine[:memory]
        libvirt.cpus = machine[:cpus]
      end

      # Préparation de chaque machine.
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "confs/ansible/bootstrap.yml"

        # IMPORTANT :
        # évite que Vagrant utilise l'ancien argument Ansible "--sudo".
        ansible.compatibility_mode = "2.0"

        ansible.become = true
      end

      # Une fois arrivé au worker, configuration du cluster complet.
      if name == LAST_NODE
        node.vm.provision "ansible" do |ansible|

          ansible.playbook = "confs/ansible/cluster.yml"

          # Même correction pour Ansible moderne.
          ansible.compatibility_mode = "2.0"

          ansible.limit = "all"

          ansible.groups = {
            "servers" => [SERVER],
            "workers" => [WORKER]
          }

          ansible.host_vars = {
            SERVER => {
              "ip" => NODES[SERVER][:ip]
            },

            WORKER => {
              "ip" => NODES[WORKER][:ip]
            }
          }

          ansible.become = true
        end
      end
    end
  end
end
